name: Generate documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Launch this workflow everyday at midnight

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build documentation
        run: yarn generate-build

#       - name: Create PR with updated documentation
#         run: | 
#           gh pr create -B main \
#              --title 'chore(docs): generate documentation' \
#              --body 'Automated PR'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
